point_cloud_topic: "/laser_poinclound"
map_frame_id: "map"
robot_base_frame_id: "laser_base"
robot_pose_with_covariance_topic: "/fake_pos"
sensor_frame_id: "laser_frame"
robot_pose_cache_size: 1
track_point_frame_id: "laser_base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0