sensor_processor/type: laser
#sensor_processor/min_radius: 0.018
#sensor_processor/beam_angle: 0.0006
#sensor_processor/beam_constant: 0.0015
sensor_processor/ignore_points_above: 0.5
sensor_processor/ignore_points_below: -inf
sensor_processor/apply_voxelgrid_filter: false
#sensor_processor/voxelgrid_filter_size: 3