joint:
  names: [scanner_joint]
motion:
  names: [sweep1,sweep2,sweep3]
  sweep1:
    step: [0]  # radian
    time_from_start: 3.0  # sec
  sweep2:
    step: [-1]  # radian
    time_from_start: 5.0  # sec
  sweep3:
    step: [-3]  # radian
    time_from_start: 7.0  # sec

