teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: []
    axis_mappings:
      -
        axis: 1 ## Left Analog Up down ---> Joint1
        target: linear.x
        scale: 3
        offset: 0
      -
        axis: 3 ## Right Analog Up down ---> Joint2
        target: linear.y
        scale: 3
      -
        axis: 0 ## Analog Left Right ---> Bucket
        target: linear.z
        scale: 3
      -
        axis: 4 ## Digital Left Right ---> Swing
        target: angular.x
        scale: 3.0

      -
        axis: 5 ## Digital Up Down ---> Wheel
        target: angular.y
        scale: 3.0

 